import Head from "next/head";
import Light from "../components/Light";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sinaleira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="lights">
          <Light color="red" />
          <Light color="yellow" />
          <Light color="green" />
        </div>
      </main>
    </>
  );
}
